# Generated by Django 5.2.4 on 2025-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("pwd", models.CharField(max_length=64)),
                ("_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
