# Generated by Django 5.2.5 on 2025-09-04 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_enrollment_student_teacher_delete_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "課程", "verbose_name_plural": "課程"},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={"verbose_name": "報名記錄", "verbose_name_plural": "報名記錄"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "學生", "verbose_name_plural": "學生"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "老師", "verbose_name_plural": "老師"},
        ),
        migrations.RemoveField(
            model_name="course",
            name="teacher",
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="建立時間"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(to="courses.teacher", verbose_name="課程老師"),
        ),
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[("初級", "初級"), ("中級", "中級"), ("高級", "高級")],
                default="初級",
                max_length=20,
                verbose_name="學生等級",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bio",
            field=models.TextField(blank=True, verbose_name="老師介紹"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="課程說明"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, verbose_name="課程名稱"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
                verbose_name="課程",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="報名時間"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.student",
                verbose_name="學生",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="電子信箱"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, verbose_name="學生姓名"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="電子信箱"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=100, verbose_name="老師姓名"),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
    ]
